services:
  - type: web
    name: link-quest
    env: node
    plan: free
    rootDirectory: .

    buildCommand: npm install && npm run build
    startCommand: node server.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
